import Head from 'next/head'

function AIPHead(props: any) {
  return <Head>
    <title>AppImage Pool</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>;
}

export default AIPHead
