import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Button from '../components/Button'
import NavigationBar from '../components/NavigationBar'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>AppImage Pool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavigationBar currentPage="Home" />
        <div className="h-screen flex flex-col justify-center space-y-5 ml-150px w-380px">
          <h1 className="text-title font-bold text-accent">AppImage Pool</h1>
          <p className="text-paragraph">A simple, modern AppImageHub client powered by flutter.</p>
          <div className="flex flex-row space-x-5">
            <Button isAccented={ true } text="Download" link="#download" />
            <Button isFlat={ true } text="Documentation" link="" />
          </div>
        </div>

        <div className="absolute right-0 bottom-0">
          <Image className="rounded-tl-md" src="/app.jpg" width={2566 / 7 * 2} height={1572 / 7 * 2} />
        </div>

        <div className="h-32"></div>

        <div className="bg-secondary flex flex-col place-items-center">
          <div className="h-32"></div>
          <h1 className="text-heading-1 text-accent font-bold">Latest News</h1>
          <div className="mt-16 flex flex-row space-x-10">
            <div className="mr-60px hover:scale-105 ease-linear duration-200">
              <img src="/home.jpg" width="480"></img>
            </div>
            <div className="flex flex-col w-380px space-y-4 justify-center">
              <h2 className="text-heading-2 text-accent">Version 1.0</h2>
              <p className="text-paragraph">Some summary text blah blah blah</p>
              <div className="flex flex-row space-x-5">
                <Button isAccented={ true } text="Read More" link="/posts/somepost" />
                <Button isFlat={ true } text="View All" link="/posts" />
              </div>
            </div>
          </div>
          <div className="h-32"></div>
        </div>

        <div className="h-32"></div>

        <div id="features" className="flex flex-col space-y-32">
          <h1 className="text-accent text-heading-1 font-bold place-self-center">Features</h1>
          <div className="flex flex-row place-items-center justify-center">
            <div className="w-380px ml-60 text-right space-y-5 mr-120px">
              <h2 className="text-heading-2 text-accent">Simple Categories</h2>
              <p className="text-paragraph">All apps are sorted into categories so you can search and find what your looking for quickly</p>
            </div>
            <div className="bg-contain bg-no-repeat bg-feature-pattern">
              <img className="hover:scale-105 ease-linear duration-200" width="400" src="/category.jpg" />
            </div>
          </div>
          <div className="flex flex-row place-items-center justify-center">
            <div className="bg-contain bg-no-repeat bg-feature-pattern-flipped">
              <img className="hover:scale-105 ease-linear duration-200" width="400" src="/app.jpg" />
            </div>
            <div className="w-380px mr-60 space-y-5 ml-120px">
              <h2 className="text-heading-2 text-accent">Upgrade and Downgrade AppImages Easily</h2>
              <p className="text-paragraph">Upgrade or downgrade all apps with the click of a button</p>
            </div>
          </div>
          <div className="flex flex-row place-items-center justify-center">
            <div className="w-380px ml-60 text-right space-y-5 mr-120px">
              <h2 className="text-heading-2 text-accent">Version History and Multi Download Support</h2>
              <p className="text-paragraph">Keep multiple versions of AppImages at the same time</p>
            </div>
            <div className="bg-contain bg-no-repeat bg-feature-pattern">
              <img className="hover:scale-105 ease-linear duration-200" width="400" src="/search.jpg" />
            </div>
          </div>
          <div className="flex flex-row place-items-center justify-center">
            <div className="bg-contain bg-no-repeat bg-feature-pattern-flipped">
              <img className="hover:scale-105 ease-linear duration-200" width="400" src="/home.jpg" />
            </div>
            <div className="w-380px mr-60 space-y-5 ml-120px">
              <h2 className="text-heading-2 text-accent">Fast Downloader</h2>
              <p className="text-paragraph">Thanks to multiprocessing and parellism, AppImage Pool downloads apps extremely quickly</p>
            </div>
          </div>
        </div>

        <div className="h-32"></div>

        <a href="https://github.com/prateekmedia/appimagepool">
          <div className="flex flex-row justify-center place-items-center space-x-8">
            <p className="text-paragraph">Free and open source forever</p>
            <img src="/github.svg" width="48" height="48" />
          </div>
        </a>

        <div className="h-32"></div>

        <div id="download" className="bg-dark-1">
          <div className="h-32"></div>
          <h1 className="text-heading-1 text-accent font-bold text-center">Download</h1>
          <div className="h-32"></div>
          <div className="flex flex-row justify-center space-x-5">
            <Button isAccented={ true } text="Flatpak" />
            <Button isAccented={ true } text="AppImage" />
            <Button isAccented={ true } text="Nightly" />
          </div>
          <div className="h-48"></div>
          <div className="flex flex-row place-items-center justify-between">
            <div className="ml-150px flex flex-col text-small text-placeholder">
              <p className="font-bold">AppImagePool</p>
              <p>A simple AppImageHub client</p>
            </div>

            <div className="mr-150px">
              <a href="https://github.com/prateekmedia/appimagepool">
                <svg width="24px" height="24px" viewBox="0 0 24 24">
                  <defs>
                    <filter id="filter_1">
                    <feColorMatrix in="SourceGraphic" type="matrix" values="0 0 0 0 0.52156866 0 0 0 0 0.52156866 0 0 0 0 0.52156866 0 0 0 1 0" />
                    </filter>
                    <path d="M0 0L24 0L24 24L0 24L0 0Z" id="path_1" />
                  </defs>
                  <g id="github" filter="url(#filter_1)">
                    <path d="M0 0L24 0L24 24L0 24L0 0Z" id="Background" fill="none" fill-rule="evenodd" stroke="none" />
                    <path d="M12 0C5.37 0 0 5.37 0 12C0 17.31 3.435 21.795 8.205 23.385C8.805 23.49 9.03 23.13 9.03 22.815C9.03 22.53 9.015 21.585 9.015 20.58C6 21.135 5.22 19.845 4.98 19.17C4.845 18.825 4.26 17.76 3.75 17.475C3.33 17.25 2.73 16.695 3.735 16.68C4.68 16.665 5.355 17.55 5.58 17.91C6.66 19.725 8.385 19.215 9.075 18.9C9.18 18.12 9.495 17.595 9.84 17.295C7.17 16.995 4.38 15.96 4.38 11.37C4.38 10.065 4.845 8.985 5.61 8.145C5.49 7.845 5.07 6.615 5.73 4.965C5.73 4.965 6.735 4.65 9.03 6.195C9.99 5.925 11.01 5.79 12.03 5.79C13.05 5.79 14.07 5.925 15.03 6.195C17.325 4.635 18.33 4.965 18.33 4.965C18.99 6.615 18.57 7.845 18.45 8.145C19.215 8.985 19.68 10.05 19.68 11.37C19.68 15.975 16.875 16.995 14.205 17.295C14.64 17.67 15.015 18.39 15.015 19.515C15.015 21.12 15 22.41 15 22.815C15 23.13 15.225 23.505 15.825 23.385C20.71 21.7364 23.9991 17.1557 24 12C24 5.37 18.63 0 12 0L12 0Z" id="Shape" fill="#000000" stroke="none" />
                  </g>
                </svg>
              </a>
            </div>
          </div>
          <div className="h-16"></div>
        </div>
        <div className="bg-dark-2 flex flex-col justify-center place-items-center text-small text-placeholder">
          <div className="h-16"></div>
          {/* <p>Site design by iwoithe</p> */}
          {/* TODO: Decide on the final website license */}
          <p>Website released under the CC BY-SA 4.0 license</p>
          <div className="h-16"></div>
        </div>
      </main>
    </div>
  )
}

export default Home
